### ISSUE TITLE
Pathfinder/seat deployment

### ISSUE THREAD

**Issue by mikesmith2107** [goryn-clade/pathfinder#110]
I have recently deployed pathfinder and seAT on the same server using docker. I know some of the people deploying pathfinder are trying to do same. And finding little to no help. Is it possible if I make a full readme for installation process and and setup process, to create a fork explaining how and installation files to either have a link added to the docker-compose solution of pathfinder. 

I had to remove treafik to be standalone and handle all tls redirect and letencrypt, remove treafik from both docker-compose.yml files and change docker connection on seAT. In order for everything to work properly. Which for those that do not understand how docker or traefik work, a real nightmare. 

If this is possible please let know and I'll be sure pass on files and make the full readme installation process. Let me know!

**Comment by ghost** [comment]
Hi Mike,

have you done this part already?
I would be really interested to see how you where able to do this as indeed I want to do the same

**Comment by samoneilll** [comment]
Hi @mikesmith2107  maybe you need to fork the pathfinder-containers project? If you create a fork or another project with the config you used for SEAT I'm happy to add links to it in the readme

**Comment by mikesmith2107** [comment]
I will upload files into a project and post a link in a couple of days . Having them play along together was easy merged the dockerfile and docker-compose files.   While have to look at the first 25 pushes of the project to find the correct combined Files. Currently that project is being scripted for homepage/seat/pathfinder All in one deployment.

**Comment by fleischsalatinspace** [comment]
This is IMO more a question regarding multi docker-compose project reverse proxying with traefik. I'll paste the config of one of my running Traefik + Pathfinder/SEAT setups:

traefik listening on tcp 80/443 
make sure to create docker network `web` first with `docker network create web`
`docker-compose.yml`:
```
version: "3.8"

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${PROJECT_ROOT}/letsencrypt:/letsencrypt"
    networks:
      - web
    restart: always

networks:
    web:
       external: true

```
pathfinder `docker-compose.yml` based on https://github.com/goryn-clade/pathfinder-containers
```
version: "3.8"

services:
  pfdb:
    image: bianjp/mariadb-alpine:latest
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    container_name: "$CONTAINER_NAME-db"
    networks:
      pf:
        aliases:
          - "${CONTAINER_NAME}db"
    volumes:
     - db_data:/var/lib/mysql
     - $PROJECT_ROOT/pathfinder/export/sql/eve_universe.sql.zip:/eve_universe.sql.zip
    restart: always
  pf-redis:
    image: redis:6.2.5-alpine3.14
    container_name: "$CONTAINER_NAME-redis"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis_data:/data
    networks:
      pf:
        aliases:
          - "$CONTAINER_NAME-redis"
    logging:
      driver: none
    restart: always
  pf-socket:
    image: composer:composer@sha256:d374b2e1f715621e9d9929575d6b35b11cf4a6dc237d4a08f2e6d1611f534675
    container_name: "$CONTAINER_NAME-socket"
    command: ["sh","-c","composer install && php cmd.php --tcpHost 0.0.0.0"]
    hostname: socket
    volumes:
      - ${PROJECT_ROOT}/websocket:/app
      - ${PROJECT_ROOT}/logs:/var/www/html/pathfinder/history/map
    networks:
      pf:
         aliases:
           - "$CONTAINER_NAME-socket"
    restart: always
  pf:
    container_name: ${CONTAINER_NAME}
    hostname: "pathfinder"
    build: '.'
    env_file:
    - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.pf.loadbalancer.server.port=80"
      - "traefik.http.routers.pf.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.pf.entrypoints=web"
      - "traefik.http.routers.pf-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.pf-secure.entrypoints=websecure"
      - "traefik.http.routers.pf-secure.tls=true"
      - "traefik.http.routers.pf-secure.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.redirecthttps.redirectscheme.scheme=https"
      - "traefik.http.routers.pf.middlewares=redirecthttps"
    networks:
      - pf
      - web
    healthcheck:
      disable: true
    volumes:
      - ${PROJECT_ROOT}/config/pathfinder/config.ini:/var/www/html/pathfinder/app/templateConfig.ini
      - ${PROJECT_ROOT}/config/pathfinder/pathfinder.ini:/var/www/html/pathfinder/app/pathfinder.ini
      - ${PROJECT_ROOT}/config/pathfinder/plugin.ini:/var/www/html/pathfinder/app/plugin.ini
      - ${PROJECT_ROOT}/config/pathfinder/info_panel.html:/var/www/html/pathfinder/public/templates/ui/info_panel.html
      - ${PROJECT_ROOT}/logs:/var/www/html/pathfinder/history/map
    depends_on:
      - pfdb
      - pf-redis
      - pf-socket
    restart: always
  
volumes:
     data:
     db_data:
     redis_data:
networks:
    pf:
    web:
       external: true

```
seat `docker-compose.yml` based on https://github.com/eveseat/seat-docker
```
version: "3.2"

services:

  mariadb:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MARIADB_AUTO_UPGRADE: "yes"
      MARIADB_DISABLE_UPGRADE_BACKUP: "yes"
    volumes:
      - "mariadb-data:/var/lib/mysql"
    networks:
      - seat-network
        #    logging:
        #      driver: "json-file"
        #      options:
        #        max-size: "10Mb"
        #        max-file: "5"

  redis:
    image: redis:5-alpine
    restart: always
    networks:
      - seat-network
        #    logging:
        #      driver: "json-file"
        #      options:
        #        max-size: "10Mb"
        #        max-file: "5"
  
  seat-web:
    image: eveseat/seat:4
    restart: always
    command: web
    volumes:
      - ./packages:/var/www/seat/packages:ro  # development only
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.seat.loadbalancer.server.port=80"
      - "traefik.http.routers.seat.rule=Host(`${SEAT_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.seat.entrypoints=web"
      - "traefik.http.routers.seat-secure.rule=Host(`${SEAT_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.seat-secure.entrypoints=websecure"
      - "traefik.http.routers.seat-secure.tls=true"
      - "traefik.http.routers.seat-secure.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.redirecthttps.redirectscheme.scheme=https"
      - "traefik.http.routers.seat.middlewares=redirecthttps"
    depends_on:
      - mariadb
      - redis
    networks:
      - seat-network
      - web
        #    logging:
        #      driver: "json-file"
        #      options:
        #        max-size: "10Mb"
        #        max-file: "5"

  seat-worker:
    image: eveseat/seat:4
    restart: always
    command: worker
    volumes:
      - ./packages:/var/www/seat/packages:ro  # development only
    env_file:
      - .env
    depends_on:
      - seat-web # so that we can get db migrations done
      - mariadb
      - redis
    networks:
      - seat-network
        #    logging:
        #      driver: "json-file"
        #      options:
        #        max-size: "10Mb"
        #        max-file: "5"

  seat-cron:
    image: eveseat/seat:4
    restart: always
    command: cron
    volumes:
      - ./packages:/var/www/seat/packages:ro  # development only
    env_file:
      - .env
    depends_on:
      - seat-web # so that we can get db migrations done
      - mariadb
      - redis
    networks:
      - seat-network
        #    logging:
        #      driver: "json-file"
        #      options:
        #        max-size: "10Mb"
        #        max-file: "5"

volumes:
    mariadb-data:

networks:
    seat-network:
    web:
       external: true
```
Please note the commented blocks regarding json-logging.

> I had to remove treafik to be standalone and handle all tls redirect and letencrypt, remove treafik from both docker-compose.yml files and change docker connection on seAT. In order for everything to work properly. Which for those that do not understand how docker or traefik work, a real nightmare.
Its exactly what i did. Tbh i dont know if its possible to document setups like this for non-technical users
Maybe this can help you @mikesmith2107 ?
